GMAIL_USERNAME = ENV['GMAIL_USERNAME']
GMAIL_PWD = ENV['GMAIL_PWD']
P_USERNAME = ENV['P_USERNAME']
P_PWD = ENV['P_PWD']
REGISTER_KEY = ENV['REGISTER_KEY']
P_GVOICE_RNR = ENV['P_GVOICE_RNR']
T_GVOICE_RNR = ENV['T_GVOICE_RNR']
T_USERNAME = ENV['T_USERNAME']
T_PWD = ENV['T_PWD']



